export const pageTexts = {
  es: {
    cardName: "Nombre de la carta",
    hp: "PS",
    type: "Tipo",
    rarity: "Rareza",
    attacks: "Ataques",
    weaknesses: "Debilidades",
    description: "Descripción",
    moreInfo: "Más Información",
    home: "Inicio",
    cards: "Cartas",
    howToPlay: "Como Jugar",
    series: "Series",
    videogames: "Videojuegos",
    ods: "ODS",
    aboutUs: "Nosotros",
    odsAndTypes: "Objetivos de Desarrollo Sostenible (ODS) y Tipos Pokémon",
    odsRelatedTo: "ODS relacionada con",
    selectTypeToSeeOds: "Selecciona un tipo para ver su ODS relacionada",
    clickTypeToSeeOds: "Haz clic en un tipo de Pokémon para ver su ODS relacionada",
    footerTitle: "TCG Pokemon",
    footerDev: "2025 TCG Pokemon web. Desarrollado por Hanner Hernández, Alejando Vielma, Alejandro Rosas y Daniel Carreño",
    footerLegal: "Pokemon y todas las marcas relacionadas son propiedad de Nintendo, Game Freak y Creatures Inc"
  },
  en: {
    cardName: "Card Name",
    hp: "HP",
    type: "Type",
    rarity: "Rarity",
    attacks: "Attacks",
    weaknesses: "Weaknesses",
    description: "Description",
    moreInfo: "More Info",
    home: "Home",
    cards: "Cards",
    howToPlay: "How to Play",
    series: "Series",
    videogames: "Videogames",
    ods: "SDGs",
    aboutUs: "About Us",
    odsAndTypes: "Sustainable Development Goals (SDGs) and Pokémon Types",
    odsRelatedTo: "SDG related to",
    selectTypeToSeeOds: "Select a type to see its related SDG",
    clickTypeToSeeOds: "Click on a Pokémon type to see its related SDG",
    footerTitle: "TCG Pokemon",
    footerDev: "2025 TCG Pokemon web. Developed by Hanner Hernández, Alejando Vielma, Alejandro Rosas and Daniel Carreño",
    footerLegal: "Pokemon and all related trademarks are property of Nintendo, Game Freak and Creatures Inc"
  }
};