export const pageTexts = {
  es: {
    cardName: "Nombre de la carta",
    hp: "PS",
    type: "Tipo",
    rarity: "Rareza",
    attacks: "Ataques",
    weaknesses: "Debilidades",
    description: "Descripción",
    moreInfo: "Más Información",
    home: "Inicio",
    cards: "Cartas",
    howToPlay: "Como Jugar",
    series: "Series",
    videogames: "Videojuegos",
    ods: "ODS",
    aboutUs: "Nosotros",
    odsAndTypes: "Objetivos de Desarrollo Sostenible (ODS) y Tipos Pokémon",
    odsRelatedTo: "ODS relacionada con",
    selectTypeToSeeOds: "Selecciona un tipo para ver su ODS relacionada",
    clickTypeToSeeOds: "Haz clic en un tipo de Pokémon para ver su ODS relacionada",
    footerTitle: "TCG Pokemon",
    footerDev: "2025 TCG Pokemon web. Desarrollado por Hanner Hernández, Alejando Vielma, Alejandro Rosas y Daniel Carreño",
    footerLegal: "Pokemon y todas las marcas relacionadas son propiedad de Nintendo, Game Freak y Creatures Inc",
    enjoyTitle: "¡Disfruta!",
    enjoyDescription: "Experimenta el JCC Pokémon de una manera completamente nueva, diseñada para dispositivos móviles. Disfruta de batallas rápidas y sencillas, colecciona cartas digitales únicas con",
    odsSectionTitle: "Pokémon y Objetivos de Desarrollo Sostenible",
    odsSectionSubtitle: "Descubre cómo cada tipo de Pokémon se relaciona con los ODS de las Naciones Unidas",
    odsSectionButton: "Ver todas las relaciones",
    odsSectionCardAlt: "Tipo {type}",
    odsSectionOds: "ODS",
    odsSectionExplore: "¡Explora todos los tipos y aprende sobre los desafíos globales!",
    randomCardTitle: "Carta Pokémon aleatoria",
    randomCardLoading: "Cargando carta...",
    randomCardError: "No se pudo cargar la carta.",
    randomCardButton: "Obtener Otra Carta",
    randomCardTypeUnknown: "Tipo Desconocido",
    randomCardHP: "Puntos de Vida",
    randomCardAbility: "Habilidad",
    randomCardNoAbility: "Sin Habilidades",
    randomCardAbilityNoDesc: "Sin descripción disponible.",
    randomCardAttacks: "Ataques",
    randomCardNoAttacks: "Sin Ataques",
    randomCardWeaknesses: "Debilidades",
    randomCardNoWeaknesses: "Sin Debilidades",
    seriesSectionTitle: "Series",
    seriesSectionSubtitle: "Descubre nuestra colección de series",
    seriesSectionLoading: "Cargando series...",
    seriesSectionError: "Error al cargar las series",
    seriesSectionEmpty: "No hay series disponibles",
    seriesSectionEmptySubtitle: "Vuelve pronto para ver nuevo contenido",
    seriesSectionButton: "Ir a Series",
    tutorialSectionTitle: "Aprende a Jugar",
    tutorialSectionDescription: "Experimenta el JCC Pokémon de una manera completamente nueva, diseñada para dispositivos móviles. Disfruta de batallas rápidas y sencillas, colecciona cartas digitales únicas con",
    tutorialSectionButton: "Ir a Como Jugar",
    videogamesSectionTitle: "Videojuegos",
    videogamesSectionButton: "Ir a Videojuegos",
    advancedSearchTitle: "Busqueda Avanzada",
    advancedSearchSet: "Set",
    advancedSearchAllSets: "Todos",
    advancedSearchType: "Tipo",
    advancedSearchAllTypes: "Todos",
    advancedSearchRarity: "Rareza",
    advancedSearchAllRarities: "Todas",
    advancedSearchButton: "Buscar",
    cardStageDefault: "Pokémon",
    cardWeaknesses: "Debilidades:",
    cardNoWeaknesses: "Ninguna",
    cardExpansion: "Expansión",
    cardExpansionUnknown: "Desconocida",
    cardIllustrator: "Ilustrador",
    cardIllustratorUnknown: "Desconocido",
    cardOdsRelated: "ODS Relacionada",
    relatedCards: "Cartas Relacionadas",
    cardNotFound: "No se encontró la carta.",
    sortBy: "Ordenar por",
    sortById: "Id",
    sortByName: "Nombre",
    loadingCards: "Cargando cartas...",
    loadingMoreCards: "Cargando más cartas...",
    noCardFound: "No se ha encontrado la carta.",
    searchByName: "Buscar por nombre",
    searchBarPlaceholder: "Buscar...",
    showingCardsFromSet: "Mostrando cartas del set:",
    noCardsInSet: "No se encontraron cartas en el set",
    showingGeneralCards: "Mostrando cartas generales.",
    loadMore: "Cargar más",
    deckGeneratorTitle: "Generador de Barajas",
    deckGeneratorButton: "Ir a Generador de Barajas",
    instructionsLink: "Link de Instrucciones",
    setCardCount: "Nro de Cartas",
    setCardCountNA: "N/D",
    setReleaseDateNA: "Fecha no disponible",
    expansionsTitle: "Expansiones de",
    expansionsTitleDefault: "Pokémon Expansiones de Cartas",
    expansionsSearchPlaceholder: "Buscar expansiones...",
    expansionsSortBy: "Ordenar por",
    expansionsSortAlphabet: "Alfabeto",
    expansionsSortDate: "Fecha de emisión",
    expansionsSortCount: "Cantidad de Cartas",
    expansionsLoading: "Cargando expansiones...",
    expansionsError: "Error al cargar las expansiones.",
    expansionsNotFound: "No se encontraron expansiones."
  },
  en: {
    cardName: "Card Name",
    hp: "HP",
    type: "Type",
    rarity: "Rarity",
    attacks: "Attacks",
    weaknesses: "Weaknesses",
    description: "Description",
    moreInfo: "More Info",
    home: "Home",
    cards: "Cards",
    howToPlay: "How to Play",
    series: "Series",
    videogames: "Videogames",
    ods: "SDGs",
    aboutUs: "About Us",
    odsAndTypes: "Sustainable Development Goals (SDGs) and Pokémon Types",
    odsRelatedTo: "SDG related to",
    selectTypeToSeeOds: "Select a type to see its related SDG",
    clickTypeToSeeOds: "Click on a Pokémon type to see its related SDG",
    footerTitle: "TCG Pokemon",
    footerDev: "2025 TCG Pokemon web. Developed by Hanner Hernández, Alejando Vielma, Alejandro Rosas and Daniel Carreño",
    footerLegal: "Pokemon and all related trademarks are property of Nintendo, Game Freak and Creatures Inc",
    enjoyTitle: "Enjoy!",
    enjoyDescription: "Experience the Pokémon TCG in a whole new way, designed for mobile devices. Enjoy fast and simple battles, and collect unique digital cards with",
    odsSectionTitle: "Pokémon and Sustainable Development Goals",
    odsSectionSubtitle: "Discover how each Pokémon type relates to the United Nations SDGs",
    odsSectionButton: "See all relationships",
    odsSectionCardAlt: "Type {type}",
    odsSectionOds: "SDG",
    odsSectionExplore: "Explore all types and learn about global challenges!",
    randomCardTitle: "Random Pokémon Card",
    randomCardLoading: "Loading card...",
    randomCardError: "Could not load the card.",
    randomCardButton: "Get Another Card",
    randomCardTypeUnknown: "Unknown Type",
    randomCardHP: "Hit Points",
    randomCardAbility: "Ability",
    randomCardNoAbility: "No Abilities",
    randomCardAbilityNoDesc: "No description available.",
    randomCardAttacks: "Attacks",
    randomCardNoAttacks: "No Attacks",
    randomCardWeaknesses: "Weaknesses",
    randomCardNoWeaknesses: "No Weaknesses",
    seriesSectionTitle: "Series",
    seriesSectionSubtitle: "Discover our series collection",
    seriesSectionLoading: "Loading series...",
    seriesSectionError: "Error loading series",
    seriesSectionEmpty: "No series available",
    seriesSectionEmptySubtitle: "Check back soon for new content",
    seriesSectionButton: "Go to Series",
    tutorialSectionTitle: "Learn to Play",
    tutorialSectionDescription: "Experience the Pokémon TCG in a whole new way, designed for mobile devices. Enjoy fast and simple battles, and collect unique digital cards.",
    tutorialSectionButton: "Go to How to Play",
    videogamesSectionTitle: "Videogames",
    videogamesSectionButton: "Go to Videogames",
    advancedSearchTitle: "Advanced Search",
    advancedSearchSet: "Set",
    advancedSearchAllSets: "All",
    advancedSearchType: "Type",
    advancedSearchAllTypes: "All",
    advancedSearchRarity: "Rarity",
    advancedSearchAllRarities: "All",
    advancedSearchButton: "Search",
    cardStageDefault: "Pokémon",
    cardWeaknesses: "Weaknesses:",
    cardNoWeaknesses: "None",
    cardExpansion: "Expansion",
    cardExpansionUnknown: "Unknown",
    cardIllustrator: "Illustrator",
    cardIllustratorUnknown: "Unknown",
    cardOdsRelated: "Related SDG",
    relatedCards: "Related Cards",
    cardNotFound: "Card not found.",
    sortBy: "Sort by",
    sortById: "Id",
    sortByName: "Name",
    loadingCards: "Loading cards...",
    loadingMoreCards: "Loading more cards...",
    noCardFound: "No card found.",
    searchByName: "Search by name",
    searchBarPlaceholder: "Search...",
    showingCardsFromSet: "Showing cards from set:",
    noCardsInSet: "No cards found in set",
    showingGeneralCards: "Showing general cards.",
    loadMore: "Load more",
    deckGeneratorTitle: "Deck Generator",
    deckGeneratorButton: "Go to Deck Generator",
    instructionsLink: "Instructions Link",
    setCardCount: "Card Count",
    setCardCountNA: "N/A",
    setReleaseDateNA: "Release date not available",
    expansionsTitle: "Expansions of",
    expansionsTitleDefault: "Pokémon Card Expansions",
    expansionsSearchPlaceholder: "Search expansions...",
    expansionsSortBy: "Sort by",
    expansionsSortAlphabet: "Alphabet",
    expansionsSortDate: "Release date",
    expansionsSortCount: "Card Count",
    expansionsLoading: "Loading expansions...",
    expansionsError: "Error loading expansions.",
    expansionsNotFound: "No expansions found."
  }
};